version: '3'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
